database:
  environments:
    -
      name: mysql1
      username: root
      password: user
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testDB?insecureAuth=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    -
      name: mysql2
      username: root
      password: user
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testDB?insecureAuth=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false

logging.level.org.springframework.jdbc : INFO